from enum import StrEnum


class AuthorityLevel(StrEnum):
    NATIONAL_LAW = "NATIONAL_LAW"
    NHNN_CIRCULAR = "NHNN_CIRCULAR"
    NHNN_DECISION = "NHNN_DECISION"
    INTERNAL_POLICY = "INTERNAL_POLICY"
    DEPARTMENT_SOP = "DEPARTMENT_SOP"
    FAQ = "FAQ"
    UNKNOWN = "UNKNOWN"
