from enum import StrEnum


class IngestionStatus(StrEnum):
    QUEUED = "QUEUED"
    PARSING = "PARSING"
    EXTRACTING_METADATA = "EXTRACTING_METADATA"
    CLASSIFYING = "CLASSIFYING"
    EXTRACTING_RELATIONSHIPS = "EXTRACTING_RELATIONSHIPS"
    CHUNKING = "CHUNKING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
